# Generated by Django 4.0.4 on 2022-07-14 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm', models.PositiveIntegerField()),
                ('md', models.PositiveIntegerField()),
                ('lg', models.PositiveIntegerField()),
                ('xl', models.PositiveIntegerField()),
                ('xxl', models.PositiveIntegerField()),
                ('clothingItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.products')),
            ],
        ),
    ]
