# Generated by Django 4.0.4 on 2022-07-14 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prodSizes',
        ),
        migrations.AlterField(
            model_name='sizes',
            name='clothingItem',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.products'),
        ),
    ]
