# Generated by Django 4.0.4 on 2022-07-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_prodsizes_alter_sizes_clothingitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prodAdded',
            new_name='dateAdded',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prodID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prodName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prodPrice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prodSale',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prodSalesPercent',
            new_name='salesPercent',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prodSeason',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prodType',
            new_name='type',
        ),
    ]
