# Generated by Django 4.0.4 on 2022-07-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_prodadded_products_dateadded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pic',
            field=models.ImageField(default='product_image.jpg', upload_to=''),
        ),
    ]
