# Generated by Django 4.0.4 on 2022-07-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pic',
            field=models.ImageField(default='product_image.jpg', upload_to='media/'),
        ),
    ]
