# Generated by Django 4.0.4 on 2022-07-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('productInstance', models.PositiveIntegerField()),
                ('numberOrdered', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.BooleanField(verbose_name=False)),
                ('salesPercent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.CharField(max_length=70)),
                ('season', models.CharField(max_length=70)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
